### ISSUE TITLE
Error msg on "Contains"; some other words don't get highlighted

### ISSUE THREAD

**Issue by aselker** [blahgeek/neovim-colorcoder#1]
Some files that have a line where the first word is "Contains" seems to cause an error.  For example, a file consisting only of "Contains word" causes this.  The error happens on load and on many editing operations.

Compare: https://github.com/guns/vim-clojure-static/pull/52

"Concealends" and "Oneline" don't cause errors, but also don't get highlighted.

Here's the error (copied from the editor, is there a better way to grab it?):
```
error caught in async handler '/home/my_username/.local/share/nvim/plugged/neovim-colorcoder/rplugin/python3/colorcoder.py:command:ColorcoderUpdate [1]'
Traceback (most recent call last):
  File "/home/my_username/.local/share/nvim/plugged/neovim-colorcoder/rplugin/python3/colorcoder.py", line 101, in update_full
    return self._update('\n'.join(buf.api.get_lines(0, -1, False)), bang)
  File "/home/my_username/.local/share/nvim/plugged/neovim-colorcoder/rplugin/python3/colorcoder.py", line 94, in _update
    .format(idx, ' '.join(wlist)))
  File "/home/my_username/.local/share/nvim/plugged/neovim-colorcoder/rplugin/python3/colorcoder.py", line 25, in __exit__
    self.vim.command(' | '.join(self.cmds))
  File "/home/my_username/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/my_username/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/my_username/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(syntax):E395: contains argument not accepted here
Press ENTER or type command to continue
```

**Comment by blahgeek** [comment]
Thanks for your report! Can you try the current master to check if it's resolved? Thanks!

**Comment by aselker** [comment]
Looks like it!  Thank you!
